### PR TITLE
Disallow module address range overlap

### LINKED ISSUE #574: Infinite loop in drgn_splay_tree_splay
```
gdb) p *parent
$1 = {parent = 0x5645e47b4310, left = 0x5645e477d770, right = 0x5645e47b4310}
(gdb) p *node
$2 = {parent = 0x5645e47b4310, left = 0x5645e477d770, right = 0x5645e47b4310}
(gdb) p *root
$3 = (struct binary_tree_node *) 0x5645e4749d10
(gdb) p **root
$4 = {parent = 0x0, left = 0x5645e4ad73f0, right = 0x5645e4a21260}
(gdb) p parent
$5 = (struct binary_tree_node *) 0x5645e47b4310
(gdb) p node
$6 = (struct binary_tree_node *) 0x5645e47b4310
(gdb) bt
#0  drgn_splay_tree_splay (root=0x5645e47a5920, node=0x5645e47b4310,
    parent=0x5645e47b4310) at ../../libdrgn/splay_tree.c:93
#1  0x00007fd995f596b3 in drgn_module_address_tree_delete_iterator (
    drgn_module_address_tree=<optimized out>, it=...) at ../../libdrgn/debug_info.c:161
#2  drgn_module_address_tree_delete_entry (drgn_module_address_tree=<optimized out>,
    entry=0x5645e47b40e0) at ../../libdrgn/debug_info.c:161
#3  drgn_module_delete_address_ranges (module=<optimized out>)
    at ../../libdrgn/debug_info.c:466
#4  drgn_module_set_address_range (module=<optimized out>, start=<optimized out>,
    end=<optimized out>) at ../../libdrgn/debug_info.c:555
#5  drgn_module_set_address_range (module=0x5645e47b4090, start=139711715549184,
    end=139711715700736) at ../../libdrgn/debug_info.c:542
#6  0x00007fd995f32f92 in Module_set_address_range (self=0x7fd994cbe6e0,
    value=<optimized out>, arg=<optimized out>) at ../../libdrgn/python/module.c:347
#7  0x00007fd99717acb1 in _PyObject_GenericSetAttrWithDict ()
   from /lib64/libpython3.12.so.1.0
#8  0x00007fd99717a18d in PyObject_SetAttr () from /lib64/libpython3.12.so.1.0
#9  0x00007fd997190d9a in _PyEval_EvalFrameDefault () from /lib64/libpython3.12.so.1.0
#10 0x00007fd997249bda in PyEval_EvalCode () from /lib64/libpython3.12.so.1.0
#11 0x00007fd99726ded1 in run_eval_code_obj () from /lib64/libpython3.12.so.1.0
#12 0x00007fd997268c69 in run_mod () from /lib64/libpython3.12.so.1.0
#13 0x00007fd997282c12 in pyrun_file () from /lib64/libpython3.12.so.1.0
#14 0x00007fd9972823dd in _PyRun_SimpleFileObject () from /lib64/libpython3.12.so.1.0
#15 0x00007fd997281b38 in _PyRun_AnyFileObject () from /lib64/libpython3.12.so.1.0
#16 0x00007fd99727a68b in Py_RunMain () from /lib64/libpython3.12.so.1.0
#17 0x00007fd997233e2b in Py_BytesMain () from /lib64/libpython3.12.so.1.0
#18 0x00007fd996e5130e in __libc_start_call_main (
    main=main@entry=0x5645a2e9b160 <main>, argc=argc@entry=6,
    argv=argv@entry=0x7fff275410a8) at ../sysdeps/nptl/libc_start_call_main.h:58
#19 0x00007fd996e513c9 in __libc_start_main_impl (main=0x5645a2e9b160 <main>, argc=6,
    argv=0x7fff275410a8, init=<optimized out>, fini=<optimized out>,
    rtld_fini=<optimized out>, stack_end=0x7fff27541098) at ../csu/libc-start.c:360

```

I'm going to look into this more still, but I encountered this on 0.0.33 while playing with my code for userspace stack traces in kernel vmcores. That code plays around a lot with the module address ranges. I have a vmcore and script that reliably reproduces this so it shouldn't be too hard to track down.

### PR DESCRIPTION
**Pull request by osandov**
To fix #574, I settled on disallowing overlap. If and when someone yells, we could add a way to force overwriting. @brenns10 any opinion?

### CODE REVIEW

File: libdrgn/debug_info.c [hunk 1]
```diff
@@ -539,10 +539,33 @@ LIBDRGN_PUBLIC bool drgn_module_address_range(const struct drgn_module *module,
...
 
+static struct drgn_error *
+drgn_check_module_address_range_overlap(struct drgn_module *module,
+					uint64_t start, uint64_t end)
+{
+	for (auto it = drgn_module_address_tree_search_le(&module->prog->dbinfo.modules_by_address,
+							  &start);
+	     it.entry && it.entry->start < end;
+	     it = drgn_module_address_tree_next(it)) {
+		if (start < it.entry->end && it.entry->module != module) {
```
Comment (brenns10) [inline libdrgn/debug_info.c]: Nice check to avoid raising an error if the new address ranges overlap with the old ones for the same module.

**Review by brenns10 — APPROVED** [review]
Thank you for root causing and fixing this one!
