### PR TITLE
libdrgn: Add support for looking up reading kernel parameters

### LINKED ISSUE #36: Add helper for getting kernel CONFIG options
If the kernel was compiled with `CONFIG_IKCONFIG=y`, then the gzipped kernel configuration exists in kernel memory (see [here](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/kernel/configs.c?h=v5.5-rc5)). We can't access it currently:

```
>>> prog.variable('kernel_config_data')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
LookupError: could not find variable 'kernel_config_data'
```

This is because `kernel_config_data` and `kernel_config_end` are defined in assembly. We'll need to add an interface for looking up ELF symbols by name.

### PR DESCRIPTION
**Pull request by jgkamat**
Since this is my first diff, I would appreciate it if you took a closer look than you normally do, to make sure I'm not overlooking anything.

This should be following the methodology set in #36 pretty exactly. Let me know if anything can be improved though!

I'm not sure if these tests will be fine, if CONFIG_IKCONFIG is not set (as is the case on most systems) I think the test will fail as is. Do you have a way to skip the test in this case, without preventing it from failing if the functionality is actually broken?

Closes #36

### CODE REVIEW

File: libdrgn/program.c [hunk 1]
```diff
@@ -995,3 +1001,64 @@ drgn_program_member_info(struct drgn_program *prog, struct drgn_type *type,
...
+
+	for (int i = symtab_offset; i < symtab_len; i++) {
+		const char *name = dwfl_module_getsym_info(
+			dwfl_module, i, &elf_sym, &elf_addr, NULL, NULL, NULL);
+
+		if (strcmp(sym->name, name) == 0) {
+			sym->symbol->name = name;
+			sym->symbol->address = elf_addr;
+			sym->symbol->size = elf_sym.st_size;
+			return DWARF_CB_ABORT;
```
Comment (jgkamat) [inline libdrgn/program.c]: I don't like this method of signalling success on ABORT, but I'm not sure if there's another way to cleanly get the exit status from the caller. Would you prefer setting a field in `sym` to determine success instead?

File: libdrgn/program.c [hunk 2]
```diff
@@ -995,3 +1001,64 @@ drgn_program_member_info(struct drgn_program *prog, struct drgn_type *type,
...
+	const char *module_name,
+	Dwarf_Addr base, void *arg)
+{
+	GElf_Sym elf_sym;
+	GElf_Addr elf_addr;
+	struct drgn_string_symbol *sym;
+	int symtab_offset, symtab_len;
+
+	sym = arg;
+	symtab_len = dwfl_module_getsymtab(dwfl_module);
```
Comment (jgkamat) [inline libdrgn/program.c]: I'm not sure if I should be handling errors for these `dwfl` calls in any way. Am I missing a check on these calls (and what would that look like)?

File: drgn/helpers/linux/kernel_config.py [hunk 3]
```diff
@@ -0,0 +1,54 @@
...
+    except KeyError:
+        pass
+
+    try:
+        start = prog.symbol("kernel_config_data").address
+        end = prog.symbol("kernel_config_data_end").address
+    except LookupError as e:
+        print("Kernel configuration data not found. Ensure your kernel is "
+              "compiled with CONFIG_IKCONFIG set.", file=sys.stderr)
+        raise e
```
Comment (osandov) [inline drgn/helpers/linux/kernel_config.py]: I consider the helpers library code, so rather than printing, this information should go in an exception:

```
except LookupError:
    raise LookupError("kernel configuration data not found; kernel must be compiled with CONFIG_IKCONFIG")
```

File: libdrgn/program.c [hunk 4]
```diff
@@ -995,3 +1001,64 @@ drgn_program_member_info(struct drgn_program *prog, struct drgn_type *type,
...
+
+	err = drgn_program_get_dwfl(prog, &dwfl);
+	if (err)
+		return err;
+
+	if (dwfl_getmodules(dwfl, drgn_dwarf_module_iterate_sym_table, &arg, 0)) {
+		*ret = arg.symbol;
+		return NULL;
+	}
+	// If we did a full iteration, we didn't find anything.
```
Comment (osandov) [inline libdrgn/program.c]: The allocated symbol is being leaked in the not found case.

File: tests/helpers/linux/test_kernel_config.py [hunk 5]
```diff
@@ -0,0 +1,15 @@
+import os
+import os.path
+import typing
+
+from drgn.helpers.linux import kernel_config
+
+from tests.helpers.linux import LinuxHelperTestCase
+
+
+class TestBlock(LinuxHelperTestCase):
```
Comment (osandov) [inline tests/helpers/linux/test_kernel_config.py]: `TestKconfig`?

File: tests/helpers/linux/test_kernel_config.py [hunk 6]
```diff
@@ -0,0 +1,15 @@
...
+    def test_kernel_config(self):
+        # TODO skip this test when CONFIG_IKCONFIG is not set.
+        m = kernel_config.kconfig(self.prog)
+        assert isinstance(m, typing.Mapping)
+        assert m['CONFIG_IKCONFIG'] in {'y', 'm'}
```
Comment (osandov) [inline tests/helpers/linux/test_kernel_config.py]: `self.assertTrue()` and `self.assertIn()` to get nicer output on failure.

**Comment by osandov** [comment]
As for the test case, let's only run it if `/proc/config.gz` exists. If not, the test can call `self.skipTest()`.

We could also base it on the existence of the `kernel_config_data` symbol (e.g., by looking at `/proc/kallsyms` or with `prog.symbol()`) to support the test on systems with `CONFIG_IKCONFIG` but not `CONFIG_IKCONFIG_PROC`. However, this has the major downside that if the symbol name changes or is removed for some reason, the test will start skipping silently rather than failing. In my opinion the stricter config requirement is the better option.

File: libdrgn/program.c (hunk 4 above)
Comment (jgkamat) [reply libdrgn/program.c]: Thanks for catching this, it totally slipped my mind

**Comment by jgkamat** [comment]
Seems like travis dosen't like the skipping that I implemented. It's possible I made a mistake, or that travis dosen't have CONFIG_IKCONFIG set but somehow has /proc/config.gz present (?). I'll take a look at that hopefully later today.

**Comment by osandov** [comment]
I'll take a look at the code later today, but I think what's going on is that `CONFIG_IKCONFIG` works differently on older kernels -- see https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=13610aa908dcfce77135bb799c0a10d0172da6ba. We'll want the helper to support that, too.

File: libdrgn/program.c [hunk 7]
```diff
@@ -995,3 +995,83 @@ drgn_program_member_info(struct drgn_program *prog, struct drgn_type *type,
...
+	sym = arg;
+	sym->err = NULL;
+
+	symtab_len = dwfl_module_getsymtab(dwfl_module);
+	symtab_offset = dwfl_module_getsymtab_first_global(dwfl_module);
+
+	if (symtab_len == -1 || symtab_offset == -1) {
+		sym->err = drgn_error_format(DRGN_ERROR_LOOKUP,
+			"could not look up symbol table for %s.", module_name);
+		return DWARF_CB_ABORT;
```
Comment (osandov) [inline libdrgn/program.c]: You know what, it's probably not a great idea to fail all symbol lookups hard because one file has a bad symbol table. Let's just skip the module in this case by returning `DWARF_CB_OK`.

File: libdrgn/program.c [hunk 8]
```diff
@@ -995,3 +995,83 @@ drgn_program_member_info(struct drgn_program *prog, struct drgn_type *type,
...
+	}
+
+	for (int i = symtab_offset; i < symtab_len; i++) {
+		const char *name = dwfl_module_getsym_info(
+			dwfl_module, i, &elf_sym, &elf_addr, NULL, NULL, NULL);
+
+		if (strcmp(sym->name, name) == 0) {
```
Comment (osandov) [inline libdrgn/program.c]: `dwfl_module_getsym_info()` returns `NULL` on error, so let's make this `if (name && strcmp(sym->name, name) == 0)` (again, skipping bad data rather than failing hard).

File: libdrgn/program.c [hunk 9]
```diff
@@ -995,3 +995,83 @@ drgn_program_member_info(struct drgn_program *prog, struct drgn_type *type,
...
+
+	struct drgn_symbol *sym;
+
+	err = drgn_program_get_dwfl(prog, &dwfl);
+	if (err)
+		return err;
+
+	sym = malloc(sizeof(*sym));
+	arg.name = name;
+	arg.symbol = sym;
```
Comment (osandov) [inline libdrgn/program.c]: Rather than always allocating the symbol upfront, let's allocate it only when we find it in the callback.

File: libdrgn/program.c [hunk 10]
```diff
@@ -995,3 +995,83 @@ drgn_program_member_info(struct drgn_program *prog, struct drgn_type *type,
...
+drgn_program_find_symbol_by_name(struct drgn_program *prog,
+			const char *name, struct drgn_symbol **ret)
+{
+	struct drgn_string_symbol arg;
+	struct drgn_error *err = NULL;
+	Dwfl *dwfl;
+
+	struct drgn_symbol *sym;
+
+	err = drgn_program_get_dwfl(prog, &dwfl);
```
Comment (osandov) [inline libdrgn/program.c]: If the program doesn't have a `Dwfl`, then there must be no symbols, so we can fail fast.

File: libdrgn/python/util.c [hunk 11]
```diff
@@ -103,6 +103,26 @@ int index_converter(PyObject *o, void *p)
 	}
 }
 
+int string_int_converter(PyObject *o, void *p)
```
Comment (osandov) [inline libdrgn/python/util.c]: Until we need this in more places, I'd rather fold it into `Program_symbol()`.

File: drgn/helpers/linux/kernel_config.py [hunk 12]
```diff
@@ -0,0 +1,52 @@
+# SPDX-License-Identifier: GPL-3.0+
+
+"""
+Kconfig
+------
+
+
+The ``drgn.helpers.linux.kconfig`` module provides helpers for reading kernel
```
Comment (osandov) [inline drgn/helpers/linux/kernel_config.py]: This says the module is `kconfig` but the file is called `kernel_config.py`. Let's stick with `kconfig.py`.

File: drgn/helpers/linux/kernel_config.py [hunk 13]
```diff
@@ -0,0 +1,52 @@
...
+configuration from memory. This is only supported if CONFIG_IKCONFIG is set.
+"""
+
+
+import sys
```
Comment (osandov) [inline drgn/helpers/linux/kernel_config.py]: This is unused now.

File: drgn/helpers/linux/kernel_config.py [hunk 14]
```diff
@@ -0,0 +1,52 @@
...
+import gzip
+import types
+
+from drgn import NULL, cast, container_of
```
Comment (osandov) [inline drgn/helpers/linux/kernel_config.py]: Ditto.

File: libdrgn/program.c (hunk 10 above)
Comment (jgkamat) [reply libdrgn/program.c]: Isn't this fail-fast behavior happening already below? Or is there another way errors are reported from this function?

File: libdrgn/python/util.c (hunk 11 above)
Comment (jgkamat) [reply libdrgn/python/util.c]: I think it would be a little more messy to have this directly inline in `Program_symbol` (and it would make `Program_symbol` rather large/complex. I decided to move the function into program.c but keep it in it's own function (rather than inline) to make it easier to refactor out if needed. Does that sound fine?

File: libdrgn/program.c (hunk 10 above)
Comment (osandov) [reply libdrgn/program.c]: Sorry, I mean something like what `drgn_program_find_symbol_by_address_internal()` does: if there is no `prog->_dicache`, immediately return the not found error instead of going through the trouble of creating the `dicache`/`dindex`/`dwfl`.

File: libdrgn/python/util.c (hunk 11 above)
Comment (osandov) [reply libdrgn/python/util.c]: Hm it's only a couple more lines of code, right?

```c
if (PyUnicode_Check(arg)) {
	const char *name;

	name = PyUnicode_AsUTF8(arg);
	if (!name)
		return NULL;
	err = drgn_program_find_symbol_by_name(&self->prog, name, &sym);
} else {
	struct index_arg address = {};

	if (!index_converter(arg, &address))
		return NULL;
	err = drgn_program_find_symbol_by_address(&self->prog,
						  address.uvalue, &sym);
}
```

`Program_symbol()` is not doing much other than interpreting the argument and passing it through to `libdrgn`.

File: libdrgn/python/program.c [hunk 15]
```diff
@@ -718,19 +718,24 @@ static StackTrace *Program_stack_trace(Program *self, PyObject *args,
 	return ret;
 }
 
-static PyObject *Program_symbol(Program *self, PyObject *args, PyObject *kwds)
+static PyObject *Program_symbol(Program *self, PyObject *address_or_name)
 {
 	static char *keywords[] = {"address", NULL};
```
Comment (osandov) [inline libdrgn/python/program.c]: This is unused now.

File: libdrgn/program.c [hunk 16]
```diff
@@ -995,3 +995,86 @@ drgn_program_member_info(struct drgn_program *prog, struct drgn_type *type,
...
+
+	sym = arg;
+	sym->err = NULL;
+
+	symtab_len = dwfl_module_getsymtab(dwfl_module);
+	symtab_offset = dwfl_module_getsymtab_first_global(dwfl_module);
+
+	if (symtab_len == -1 || symtab_offset == -1) {
+		sym->err = drgn_error_format(DRGN_ERROR_LOOKUP,
+			"could not look up symbol table for %s.", module_name);
```
Comment (osandov) [inline libdrgn/program.c]: If there are multiple modules with bad symbol tables, this leaks the previous error. I think it would suffice to have a flag that indicates that some symbol tables couldn't be read.

File: libdrgn/program.c [hunk 17]
```diff
@@ -995,3 +995,86 @@ drgn_program_member_info(struct drgn_program *prog, struct drgn_type *type,
...
+		return DWARF_CB_OK;
+	}
+
+	for (int i = symtab_offset; i < symtab_len; i++) {
+		const char *name = dwfl_module_getsym_info(
+			dwfl_module, i, &elf_sym, &elf_addr, NULL, NULL, NULL);
+
+		if (name && strcmp(sym->name, name) == 0) {
+			// Leaked to caller
+			sym->symbol = malloc(sizeof(struct drgn_symbol));
```
Comment (osandov) [inline libdrgn/program.c]: This can be even simpler if we pass the `struct drgn_symbol **ret` through the callback.

File: drgn/helpers/linux/kconfig.py [hunk 18]
```diff
@@ -0,0 +1,59 @@
...
+        return prog.cache["kconfig_options_map"]
+    except KeyError:
+        pass
+
+    try:
+        start = prog.symbol("kernel_config_data").address
+        size = prog.symbol("kernel_config_data_end").address - start
+        raw_data = prog.read(start, size)
+    except LookupError:
+        try:
```
Comment (osandov) [inline drgn/helpers/linux/kconfig.py]: We should limit the `try` block to only contain the statement that we want to handle, i.e., `prog["kernel_config_data"]`.

File: drgn/helpers/linux/kconfig.py [hunk 19]
```diff
@@ -0,0 +1,59 @@
...
+            # Try reading data in format present before kernel 5.0.
+            start = prog['kernel_config_data'].address_
+            size = len(prog['kernel_config_data'])
+            raw_data = prog.read(start, size)
+            trim_left = raw_data.find(b'IKCFG_ST') + len(b'IKCFG_ST')
+            trim_right = raw_data.rfind(b'IKCFG_ED')
+            if trim_left == -1 or trim_right == -1:
```
Comment (osandov) [inline drgn/helpers/linux/kconfig.py]: I don't think we need to actually find the delimiters; they're guaranteed to be at the start and end of the array.

File: drgn/helpers/linux/kconfig.py [hunk 20]
```diff
@@ -0,0 +1,59 @@
...
+                raise KeyError("IKCFG not Found")
+            raw_data = raw_data[trim_left:trim_right]
+        except KeyError:
+            raise LookupError("kernel configuration data not found; kernel must be compiled with CONFIG_IKCONFIG")
+
+    raw_options = gzip.decompress(raw_data).decode().split('\n')
```
Comment (osandov) [inline drgn/helpers/linux/kconfig.py]: `splitlines()`

File: drgn/helpers/linux/kconfig.py [hunk 21]
```diff
@@ -0,0 +1,59 @@
...
+
+    result = {}
+
+    for line in raw_options:
+        if not line or line.startswith('#'):
+            continue
+        split_option = line.split('=')
```
Comment (osandov) [inline drgn/helpers/linux/kconfig.py]: This is slightly cleaner using `line.partition('=')`.
